### ISSUE TITLE
Must fix TagBot

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#627]
TagBot does not work. This means, that a GitHub release is not being created after a new package version is accepted into the general registry.

**This is a big problem**, because it is the GitHub release that triggers new documentation generation for stable versions. E.g., at the moment our documentation does not have version 5.3, which is the version where schedulers changed. All examples still use old schedulers.

**Comment by fbanning** [comment]
I'm using TagBot without any problems on the OSMMakie repo. I did not include the following lines in my `TagBot.yaml` so maybe that's what's causing the troubles?

https://github.com/JuliaDynamics/Agents.jl/blob/main/.github/workflows/TagBot.yml#L7-L11

So it might be a permissions issue. The TagBot repo recommends the following:

```
permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
```

Might be worth a try to put this in our yaml file as well and see if that fixes the problem. If not, we could just remove lines 7-11 and see if that fixes it.
